"""CLI entry point for valutech-docs-init.

Generates .valutech-docs-base.yml in the current directory by reading the
base config template from the installed package and resolving the
__VALUTECH_PACKAGE_DIR__ placeholder to an absolute path.
"""

from pathlib import Path

OUTPUT_FILE = ".valutech-docs-base.yml"
PLACEHOLDER = "__VALUTECH_PACKAGE_DIR__"
HEADER = (
    "# AUTO-GENERATED by valutech-docs-init — do not edit.\n"
    "# Re-run `valutech-docs-init` to regenerate.\n\n"
)


def main() -> None:
    package_dir = Path(__file__).resolve().parent
    template_path = package_dir / "mkdocs-base.yml"

    if not template_path.exists():
        raise SystemExit(f"Error: base template not found at {template_path}")

    content = template_path.read_text(encoding="utf-8")
    content = content.replace(PLACEHOLDER, package_dir.as_posix())

    output = Path.cwd() / OUTPUT_FILE
    output.write_text(HEADER + content, encoding="utf-8")
    print(f"Generated {output}")


if __name__ == "__main__":
    main()
