"""CLI entry point for valutech-docs-init.

Generates .valutech-docs-base.yml in the current directory by reading the
base config template from the installed package and resolving the
__VALUTECH_PACKAGE_DIR__ placeholder to an absolute path.

With --with-api it additionally copies the Static Web Apps managed function
backing the comment widget into ./api, so a consuming project never has to
vendor that code. Both outputs are generated artefacts and belong in
.gitignore.
"""

import argparse
import shutil
from pathlib import Path

OUTPUT_FILE = ".valutech-docs-base.yml"
PLACEHOLDER = "__VALUTECH_PACKAGE_DIR__"
HEADER = (
    "# AUTO-GENERATED by valutech-docs-init — do not edit.\n"
    "# Re-run `valutech-docs-init` to regenerate.\n\n"
)

API_MARKER = ".valutech-generated"
"""Written into the copied API directory so a later run may replace it."""

API_MARKER_TEXT = (
    "Generated by `valutech-docs-init --with-api` from the valutech-docs-template\n"
    "package. Do not edit — changes belong in the template repository.\n"
)


def write_base_config(package_dir: Path) -> Path:
    template_path = package_dir / "mkdocs-base.yml"
    if not template_path.exists():
        raise SystemExit(f"Error: base template not found at {template_path}")

    content = template_path.read_text(encoding="utf-8").replace(PLACEHOLDER, package_dir.as_posix())

    output = Path.cwd() / OUTPUT_FILE
    output.write_text(HEADER + content, encoding="utf-8")
    return output


def write_api(package_dir: Path, target: Path) -> Path:
    source = package_dir / "api"
    if not source.exists():
        raise SystemExit(f"Error: bundled API not found at {source}")

    if target.exists():
        # Only ever replace a directory this command created itself.
        if not (target / API_MARKER).exists():
            raise SystemExit(
                f"Error: {target} exists and was not generated by valutech-docs-init.\n"
                "Move it aside or pass --api-dir with a different path."
            )
        shutil.rmtree(target)

    shutil.copytree(source, target, ignore=shutil.ignore_patterns("__pycache__", "node_modules"))
    (target / API_MARKER).write_text(API_MARKER_TEXT, encoding="utf-8")
    return target


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="valutech-docs-init",
        description="Generate the local MkDocs base config for a ValuTech docs project.",
    )
    parser.add_argument(
        "--with-api",
        action="store_true",
        help="also copy the comment-widget API (Static Web Apps managed function) into ./api",
    )
    parser.add_argument(
        "--api-dir",
        default="api",
        help="destination for --with-api (default: api)",
    )
    args = parser.parse_args()

    package_dir = Path(__file__).resolve().parent

    print(f"Generated {write_base_config(package_dir)}")

    if args.with_api:
        print(f"Generated {write_api(package_dir, Path.cwd() / args.api_dir)}/ (comment API)")


if __name__ == "__main__":
    main()
